name: cd

on:
  workflow_dispatch: #github页面手动触发
  push: #push即触发
    branches:
      - main
    paths-ignore: #不作为触发的文件
      - '.*'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.*'
      - 'LICENSE'
      - 'README.md'

jobs:
  cd:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:

      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          # SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "git@github.com:${{ github.repository }}.git"
          destination-repo: "github@wx.wtjzy.com:/mnt/www/git_bare/test.git"
