name: ci
on:
  workflow_dispatch: #github页面手动触发
  push: #push即触发
    branches:
      - master
    paths-ignore: #不作为触发的文件
      - '.*'
      - 'LICENSE'
      - 'README.md'
jobs:
  unit-test:
    runs-on: ubuntu-20.04 #虚拟环境(github提供)
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: restart-mysql #该ubuntu-20.04自带mysql8.0
        run: sudo systemctl restart mysql
      - name: create-db
        run: sudo mysqladmin -uroot -proot create trojan
      - name: save-data
        run: sudo mysql -uroot -proot trojan < src/data/users.sql
      - name: find1
        run: |
          sudo mkdir /usr/local/etc/php/
          sudo echo "[php]" > /usr/local/etc/php/php.ini
          sudo echo " " >> /usr/local/etc/php/php.ini
          sudo echo " " >> /usr/local/etc/php/php.ini
          sudo sed '2 imysql.default_socket=/var/run/mysqld/mysqld.sock' -i /usr/local/etc/php/php.ini
          sudo sed '2 imysqli.default_socket=/var/run/mysqld/mysqld.sock' -i /usr/local/etc/php/php.ini
          sudo sed '$a[Pdo_mysql]' -i /usr/local/etc/php/php.ini
          sudo sed '$apdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' -i /usr/local/etc/php/php.ini
      - name: find3
        run: sudo cat /usr/local/etc/php/php.ini
      - name: find4
        run: sudo systemctl restart php7.4-fpm
      - uses: php-actions/phpunit@v2
        with:
          configuration: ./phpunit.xml
          version: 9.5.2
          php_version: 7.4
          php_extensions: xdebug mbstring mysqli pdo_mysql
      - name: find5
        run: sudo ls /usr/
      - name: find7
        run: sudo ls /usr/local/
      - name: find8
        run: sudo ls /usr/local/etc/
      - name: find6
        run: sudo cat /usr/local/etc/php/php.ini

