name: ci
on:
  push: #push即触发
    tags:
      - "v*.*"
env:
  REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE: twbtest

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      tags: ${{ steps.set-output.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - name: set-output
        run: |
          DOCKER_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.DOCKER_IMAGE }}
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
  github-Packages:
    needs: prepare
    runs-on: ubuntu-20.04
    # strategy: ${{ needs.prepare.outputs.tags }}
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ needs.prepare.outputs.tags }}
