name: ci
on:
  workflow_dispatch: #github页面手动触发
  push: #push即触发
    branches:
      - master
    paths-ignore: #不作为触发的文件
      - '.*'
      - 'LICENSE'
      - 'README.md'
jobs:
  unit-test:
    runs-on: ubuntu-20.04 #虚拟环境(github提供)
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: restart-mysql #该ubuntu-20.04自带mysql8.0
        run: sudo systemctl restart mysql
      - name: create-db
        run: sudo mysqladmin -uroot -proot create trojan
      - name: save-data
        run: sudo mysql -uroot -proot trojan < src/data/users.sql
      # - name: find5
      #   run: sudo systemctl restart php7.4-fpm
      - name: find1
        run: php -m
      - name: find2
        run: |
          sudo brew search php74-xdebug
          sudo brew install php74-xdebug
          sudo brew services restart php74
      - name: find3
        run: php -m
      - uses: php-actions/phpunit@v2
        with:
          configuration: ./phpunit.xml
          version: 9.5.2
          php_version: 7.4
          php_extensions: xdebug mbstring mysqli pdo_mysql

