name: ci
on:
  push: #push即触发
    tags:
      - "v*.*"
env:
  IMAGE_NAME: test

jobs:

  get-tags:
    runs-on: ubuntu-20.04
    outputs:
      tags: ${{ steps.set-output-id.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - name: set-output
        id: set-output-id
        run: | #https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/release.yml
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo ::set-output name=tags::${VERSION}

  push-ghcr:
    needs: get-tags
    runs-on: ubuntu-20.04
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.get-tags.outputs.tags }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
      # - name: Delete Package
      #   uses: actions/delete-package-versions@v1
      #   with:
      #     package-name: ${{ env.IMAGE_NAME }}
      #     num-old-versions-to-delete: 1 #删除最旧的一个包
